services:
  db:
    image: mongo:latest
    container_name: chat_app_db
    restart: 'no'
    environment:
      MONGO_INITDB_ROOT_USERNAME: fadi
      MONGO_INITDB_ROOT_PASSWORD: 0000
      MONGO_INITDB_DATABASE: chat
    volumes:
      - chat_app-data:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: no
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: fadi
      ME_CONFIG_MONGODB_ADMINPASSWORD: 0000
      ME_CONFIG_MONGODB_URL: mongodb://localhost:27017/chat/
      ME_CONFIG_BASICAUTH: false

  api:
    build: ./server
    container_name: chat_app_backend
    ports:
      - 5000:5000
    volumes:
      - ./server:/backend
      - /backend/node_modules
    restart: 'no'
    links:
      - db

  web:
    build: ./client
    container_name: chat_app_frontend
    ports:
      - 3000:3000
    env_file:
      - ./client/.docker.env
    volumes:
      - ./client:/frontend
      - /frontend/node_modules
    restart: 'no'
    links:
      - api

volumes:
  chat_app-data:
